"""Resource management modules."""

from .audit import (
    AuditedConsentManager,
    AuditEvent,
    AuditEventType,
    AuditLog,
    AuditQueryBuilder,
    AuditReport,
    AuditSeverity,
    AuditStatistics,
    AuditStorage,
    ComplianceReportSection,
    FileAuditStorage,
    MemoryAuditStorage,
    create_audit_log,
    create_audited_manager,
)
from .consent import (
    CATEGORY_CONFIGS,
    ConsentCategory,
    ConsentCategoryConfig,
    ConsentCheckResult,
    ConsentDeniedException,
    ConsentLevel,
    ConsentManager,
    ConsentPrompt,
    ConsentRecord,
    ConsentRequest,
    ConsentResponse,
    DefaultConsentPrompt,
    requires_consent,
    # New: Consent Audit Logging
    AuditEventType as ConsentAuditEventType,
    AuditLogEntry,
    ConsentAuditLogger,
    # New: Consent Expiration & Re-prompting
    ExpirationPolicy,
    DEFAULT_EXPIRATION_POLICIES,
    ConsentExpirationManager,
    # New: Force Execute with Warnings
    ForceExecuteWarning,
    ForceExecuteResult,
    ForceExecuteManager,
    # New: Enhanced Consent Manager
    EnhancedConsentManager,
    # Edge case consent (3% gap)
    ConsentConflictType,
    ConsentEdgeCaseType,
    ConsentConflict,
    EdgeCaseResolution,
    ConsentConflictResolver,
    EdgeCaseConsentHandler,
)
from .control import (
    AbortException,
    CheckpointData,
    CheckpointManager,
    ControlEvent,
    ControlSignal,
    ControlState,
    ExecutionController,
    PauseException,
    # Distributed rollback (2% gap)
    DistributedNodeState,
    DistributedNode,
    DistributedRollbackResult,
    TwoPhaseCommitProtocol,
    DistributedTransaction,
    DistributedRollbackCoordinator,
)
from .hooks import (
    BaseConsentHandler,
    CallbackHandler,
    CategoryBlacklistPolicy,
    ConsentEvent,
    ConsentEventBus,
    ConsentEventHandler,
    ConsentEventKind,
    ConsentPolicy,
    EventAwareConsentManager,
    FilteredHandler,
    ForceOverridePolicy,
    LoggingHandler,
    MetricsHandler,
    PolicyHandler,
    PolicyViolation,
    RateLimitHandler,
    RateLimitPolicy,
    create_event_bus_with_logging,
    create_event_bus_with_metrics,
    on_consent_event,
)
from .monitor import (
    CPUMonitor,
    MemoryAlert,
    MemoryCheckResult,
    MemoryEstimate,
    MemoryEstimator,
    MemoryLevel,
    MemoryMonitor,
    MemorySnapshot,
    MemoryThresholds,
    ResourceMonitor,
    # New: Trend Analysis & Prediction
    TrendDirection,
    TrendPrediction,
    ResourceTrend,
    TrendAnalyzer,
    # New: Automatic Resource Optimization
    OptimizationType,
    OptimizationRecommendation,
    OptimizationPlan,
    ResourceOptimizer,
    # New: Backend Integration
    BackendResourceScore,
    ResourceAwareSelection,
    BackendResourceIntegration,
    # Extended monitors
    GPUSnapshot,
    GPUMonitor,
    DiskSnapshot,
    DiskMonitor,
    NetworkSnapshot,
    NetworkMonitor,
    ResourceSnapshot,
    ExtendedResourceMonitor,
)
from .session import Session, SessionManager, SessionStatus
from .timer import (
    DisplayController,
    DisplayUpdate,
    ETACalculator,
    ExecutionTimer,
    ProgressTracker,
    StageInfo,
    UpdateReason,
    # Display polish (2% gap)
    DisplayTheme,
    DisplayConfig,
    DisplayFormatter,
    LiveDisplayController,
)

__all__ = [
    # Timer (Step 4.2)
    "ExecutionTimer",
    "ProgressTracker",
    "ETACalculator",
    "StageInfo",
    "DisplayController",
    "DisplayUpdate",
    "UpdateReason",
    # Display polish (2% gap)
    "DisplayTheme",
    "DisplayConfig",
    "DisplayFormatter",
    "LiveDisplayController",
    # Monitor (Step 4.1)
    "ResourceMonitor",
    "MemoryMonitor",
    "CPUMonitor",
    "MemoryLevel",
    "MemoryThresholds",
    "MemorySnapshot",
    "MemoryAlert",
    "MemoryEstimator",
    "MemoryEstimate",
    "MemoryCheckResult",
    # Monitor - Trend Analysis & Prediction (100% Complete)
    "TrendDirection",
    "TrendPrediction",
    "ResourceTrend",
    "TrendAnalyzer",
    # Monitor - Automatic Resource Optimization (100% Complete)
    "OptimizationType",
    "OptimizationRecommendation",
    "OptimizationPlan",
    "ResourceOptimizer",
    # Monitor - Backend Integration (100% Complete)
    "BackendResourceScore",
    "ResourceAwareSelection",
    "BackendResourceIntegration",
    # Monitor - Extended Resource Monitors
    "GPUSnapshot",
    "GPUMonitor",
    "DiskSnapshot",
    "DiskMonitor",
    "NetworkSnapshot",
    "NetworkMonitor",
    "ResourceSnapshot",
    "ExtendedResourceMonitor",
    "CPUMonitor",
    "MemoryLevel",
    "MemoryThresholds",
    "MemorySnapshot",
    "MemoryAlert",
    "MemoryEstimator",
    "MemoryEstimate",
    "MemoryCheckResult",
    # Control (Step 4.3)
    "ExecutionController",
    "ControlState",
    "ControlSignal",
    "ControlEvent",
    "CheckpointData",
    "CheckpointManager",
    "AbortException",
    "PauseException",
    # Control - Distributed Rollback (2% gap)
    "DistributedNodeState",
    "DistributedNode",
    "DistributedRollbackResult",
    "TwoPhaseCommitProtocol",
    "DistributedTransaction",
    "DistributedRollbackCoordinator",
    # Consent (Step 4.4)
    "ConsentManager",
    "ConsentLevel",
    "ConsentRecord",
    "ConsentCategory",
    "ConsentCategoryConfig",
    "ConsentResponse",
    "ConsentRequest",
    "ConsentCheckResult",
    "ConsentPrompt",
    "DefaultConsentPrompt",
    "ConsentDeniedException",
    "requires_consent",
    "CATEGORY_CONFIGS",
    # Consent - Granular Types (100% Complete)
    # (Included in ConsentCategory enum expansion)
    # Consent - Audit Logging (100% Complete)
    "ConsentAuditEventType",
    "AuditLogEntry",
    "ConsentAuditLogger",
    # Consent - Expiration & Re-prompting (100% Complete)
    "ExpirationPolicy",
    "DEFAULT_EXPIRATION_POLICIES",
    "ConsentExpirationManager",
    # Consent - Force Execute with Warnings (100% Complete)
    "ForceExecuteWarning",
    "ForceExecuteResult",
    "ForceExecuteManager",
    # Consent - Enhanced Manager (100% Complete)
    "EnhancedConsentManager",
    # Consent - Edge Case Handling (3% gap)
    "ConsentConflictType",
    "ConsentEdgeCaseType",
    "ConsentConflict",
    "EdgeCaseResolution",
    "ConsentConflictResolver",
    "EdgeCaseConsentHandler",
    # Audit Logging
    "AuditEvent",
    "AuditEventType",
    "AuditSeverity",
    "AuditLog",
    "AuditStorage",
    "MemoryAuditStorage",
    "FileAuditStorage",
    "AuditQueryBuilder",
    "AuditStatistics",
    "AuditReport",
    "ComplianceReportSection",
    "AuditedConsentManager",
    "create_audit_log",
    "create_audited_manager",
    # Event Hooks
    "ConsentEventKind",
    "ConsentEvent",
    "ConsentEventHandler",
    "ConsentEventBus",
    "BaseConsentHandler",
    "LoggingHandler",
    "MetricsHandler",
    "CallbackHandler",
    "FilteredHandler",
    "PolicyHandler",
    "ConsentPolicy",
    "PolicyViolation",
    "RateLimitPolicy",
    "CategoryBlacklistPolicy",
    "ForceOverridePolicy",
    "RateLimitHandler",
    "EventAwareConsentManager",
    "create_event_bus_with_logging",
    "create_event_bus_with_metrics",
    "on_consent_event",
    # Session
    "Session",
    "SessionManager",
    "SessionStatus",
]
