"""Resource management modules."""

from .audit import (
    AuditedConsentManager,
    AuditEvent,
    AuditEventType,
    AuditLog,
    AuditQueryBuilder,
    AuditReport,
    AuditSeverity,
    AuditStatistics,
    AuditStorage,
    ComplianceReportSection,
    FileAuditStorage,
    MemoryAuditStorage,
    create_audit_log,
    create_audited_manager,
)
from .consent import (
    CATEGORY_CONFIGS,
    ConsentCategory,
    ConsentCategoryConfig,
    ConsentCheckResult,
    ConsentDeniedException,
    ConsentLevel,
    ConsentManager,
    ConsentPrompt,
    ConsentRecord,
    ConsentRequest,
    ConsentResponse,
    DefaultConsentPrompt,
    requires_consent,
)
from .control import (
    AbortException,
    CheckpointData,
    CheckpointManager,
    ControlEvent,
    ControlSignal,
    ControlState,
    ExecutionController,
    PauseException,
)
from .hooks import (
    BaseConsentHandler,
    CallbackHandler,
    CategoryBlacklistPolicy,
    ConsentEvent,
    ConsentEventBus,
    ConsentEventHandler,
    ConsentEventKind,
    ConsentPolicy,
    EventAwareConsentManager,
    FilteredHandler,
    ForceOverridePolicy,
    LoggingHandler,
    MetricsHandler,
    PolicyHandler,
    PolicyViolation,
    RateLimitHandler,
    RateLimitPolicy,
    create_event_bus_with_logging,
    create_event_bus_with_metrics,
    on_consent_event,
)
from .monitor import (
    CPUMonitor,
    MemoryAlert,
    MemoryCheckResult,
    MemoryEstimate,
    MemoryEstimator,
    MemoryLevel,
    MemoryMonitor,
    MemorySnapshot,
    MemoryThresholds,
    ResourceMonitor,
)
from .session import Session, SessionManager, SessionStatus
from .timer import (
    DisplayController,
    DisplayUpdate,
    ETACalculator,
    ExecutionTimer,
    ProgressTracker,
    StageInfo,
    UpdateReason,
)

__all__ = [
    # Timer (Step 4.2)
    "ExecutionTimer",
    "ProgressTracker",
    "ETACalculator",
    "StageInfo",
    "DisplayController",
    "DisplayUpdate",
    "UpdateReason",
    # Monitor (Step 4.1)
    "ResourceMonitor",
    "MemoryMonitor",
    "CPUMonitor",
    "MemoryLevel",
    "MemoryThresholds",
    "MemorySnapshot",
    "MemoryAlert",
    "MemoryEstimator",
    "MemoryEstimate",
    "MemoryCheckResult",
    # Control (Step 4.3)
    "ExecutionController",
    "ControlState",
    "ControlSignal",
    "ControlEvent",
    "CheckpointData",
    "CheckpointManager",
    "AbortException",
    "PauseException",
    # Consent (Step 4.4)
    "ConsentManager",
    "ConsentLevel",
    "ConsentRecord",
    "ConsentCategory",
    "ConsentCategoryConfig",
    "ConsentResponse",
    "ConsentRequest",
    "ConsentCheckResult",
    "ConsentPrompt",
    "DefaultConsentPrompt",
    "ConsentDeniedException",
    "requires_consent",
    "CATEGORY_CONFIGS",
    # Audit Logging
    "AuditEvent",
    "AuditEventType",
    "AuditSeverity",
    "AuditLog",
    "AuditStorage",
    "MemoryAuditStorage",
    "FileAuditStorage",
    "AuditQueryBuilder",
    "AuditStatistics",
    "AuditReport",
    "ComplianceReportSection",
    "AuditedConsentManager",
    "create_audit_log",
    "create_audited_manager",
    # Event Hooks
    "ConsentEventKind",
    "ConsentEvent",
    "ConsentEventHandler",
    "ConsentEventBus",
    "BaseConsentHandler",
    "LoggingHandler",
    "MetricsHandler",
    "CallbackHandler",
    "FilteredHandler",
    "PolicyHandler",
    "ConsentPolicy",
    "PolicyViolation",
    "RateLimitPolicy",
    "CategoryBlacklistPolicy",
    "ForceOverridePolicy",
    "RateLimitHandler",
    "EventAwareConsentManager",
    "create_event_bus_with_logging",
    "create_event_bus_with_metrics",
    "on_consent_event",
    # Session
    "Session",
    "SessionManager",
    "SessionStatus",
]
